// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkMonitorService.Models;

#nullable disable

namespace NetworkMonitorService.Data.Migrations
{
    [DbContext(typeof(NetworkMonitorDbContext))]
    [Migration("20250503000406_AddDiskIOColumns")]
    partial class AddDiskIOColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetworkMonitorService.Models.DiskActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesRead")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesWritten")
                        .HasColumnType("bigint");

                    b.Property<long>("OtherOperationCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReadOperationCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopOtherFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopReadFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopWriteFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WriteOperationCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DiskActivityLogs");
                });

            modelBuilder.Entity("NetworkMonitorService.Models.NetworkUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("BytesRead")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<long?>("BytesWritten")
                        .HasColumnType("bigint");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopRemoteIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NetworkUsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
